spring:
  application:
    name: physio
  datasource:
    url: jdbc:mysql://100.75.227.96:3306/alpro_physio
    username: root
    password: mysecretpassword
  jpa:
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /physio