spring:
  application:
    name: physio
  datasource:
    url: jdbc:mysql://100.75.227.96:3306/alpro_physio
    username: root
    password: mysecretpassword
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  servlet:
    context-path: /physio

app:
  api:
    base-url: http://localhost:8080

  jwt:
    secret: 4sHWaZkvUMig2+ecltlsY9pS7qirYJKGTuFDvLv+oDI=
    expiration-ms: 3600000 # 1 hour in milliseconds
  